version: "3"

services:
  malmo:
    build: docker/malmo
    container_name: malmo
    ports:
      # VNC connection
      - 5901:5901
      # VNC graphical
      - 6901:6901
      # Jupyter
      - 8822:8888
    environment:
      VNC_PW: vncpassword
    volumes:
      - ./app:/home/malmo/app
    networks:
      - minecraft

networks:
  minecraft:

